In [ ]:
import sys 
sys.path.append('../')

import matplotlib.pyplot as plt 
import mplfinance as mpf
import pandas as pd 

from main import Pipeline 

m = Pipeline('../')

ERROR: Failed to create connection for Daily Stocks: unable to open database file
2025-02-15 21:16:21,654 - ConnectionPool - ERROR - Failed to create connection for Daily Stocks: unable to open database file
ERROR: Failed to initialize pool for Daily Stocks: unable to open database file
2025-02-15 21:16:21,654 - ConnectionPool - ERROR - Failed to initialize pool for Daily Stocks: unable to open database file
ERROR: Failed to create connection for Intraday Stocks: unable to open database file
2025-02-15 21:16:21,655 - ConnectionPool - ERROR - Failed to create connection for Intraday Stocks: unable to open database file
ERROR: Failed to initialize pool for Intraday Stocks: unable to open database file
2025-02-15 21:16:21,655 - ConnectionPool - ERROR - Failed to initialize pool for Intraday Stocks: unable to open database file
ERROR: Failed to create connection for Options: unable to open database file
2025-02-15 21:16:21,656 - ConnectionPool - ERROR - Failed to create connection for Options: unable to open database file
ERROR: Failed to initialize pool for Options: unable to open database file
2025-02-15 21:16:21,656 - ConnectionPool - ERROR - Failed to initialize pool for Options: unable to open database file
ERROR: Failed to create connection for Options Read-Only: unable to open database file
2025-02-15 21:16:21,657 - ConnectionPool - ERROR - Failed to create connection for Options Read-Only: unable to open database file
ERROR: Failed to initialize pool for Options Read-Only: unable to open database file
2025-02-15 21:16:21,658 - ConnectionPool - ERROR - Failed to initialize pool for Options Read-Only: unable to open database file
ERROR: Failed to create connection for Options Changes: unable to open database file
2025-02-15 21:16:21,659 - ConnectionPool - ERROR - Failed to create connection for Options Changes: unable to open database file
ERROR: Failed to initialize pool for Options Changes: unable to open database file
2025-02-15 21:16:21,659 - ConnectionPool - ERROR - Failed to initialize pool for Options Changes: unable to open database file
ERROR: Failed to create connection for Options Volume: unable to open database file
2025-02-15 21:16:21,660 - ConnectionPool - ERROR - Failed to create connection for Options Volume: unable to open database file
ERROR: Failed to initialize pool for Options Volume: unable to open database file
2025-02-15 21:16:21,660 - ConnectionPool - ERROR - Failed to initialize pool for Options Volume: unable to open database file
ERROR: Failed to create connection for Options Stats: unable to open database file
2025-02-15 21:16:21,661 - ConnectionPool - ERROR - Failed to create connection for Options Stats: unable to open database file
ERROR: Failed to initialize pool for Options Stats: unable to open database file
2025-02-15 21:16:21,661 - ConnectionPool - ERROR - Failed to initialize pool for Options Stats: unable to open database file
ERROR: Failed to create connection for Tracking: unable to open database file
2025-02-15 21:16:21,662 - ConnectionPool - ERROR - Failed to create connection for Tracking: unable to open database file
ERROR: Failed to initialize pool for Tracking: unable to open database file
2025-02-15 21:16:21,662 - ConnectionPool - ERROR - Failed to initialize pool for Tracking: unable to open database file
ERROR: Failed to create connection for Tracking Values: unable to open database file
2025-02-15 21:16:21,663 - ConnectionPool - ERROR - Failed to create connection for Tracking Values: unable to open database file
ERROR: Failed to initialize pool for Tracking Values: unable to open database file
2025-02-15 21:16:21,663 - ConnectionPool - ERROR - Failed to initialize pool for Tracking Values: unable to open database file
ERROR: Failed to create connection for Inactive Options: unable to open database file
2025-02-15 21:16:21,663 - ConnectionPool - ERROR - Failed to create connection for Inactive Options: unable to open database file
ERROR: Failed to initialize pool for Inactive Options: unable to open database file
2025-02-15 21:16:21,664 - ConnectionPool - ERROR - Failed to initialize pool for Inactive Options: unable to open database file
ERROR: Failed to create connection for Backup Options: unable to open database file
2025-02-15 21:16:21,664 - ConnectionPool - ERROR - Failed to create connection for Backup Options: unable to open database file
ERROR: Failed to initialize pool for Backup Options: unable to open database file
2025-02-15 21:16:21,665 - ConnectionPool - ERROR - Failed to initialize pool for Backup Options: unable to open database file
ERROR: Failed to create connection for Dates: unable to open database file
2025-02-15 21:16:21,665 - ConnectionPool - ERROR - Failed to create connection for Dates: unable to open database file
ERROR: Failed to initialize pool for Dates: unable to open database file
2025-02-15 21:16:21,666 - ConnectionPool - ERROR - Failed to initialize pool for Dates: unable to open database file
ERROR: Failed to create connection for Stock Names: unable to open database file
2025-02-15 21:16:21,666 - ConnectionPool - ERROR - Failed to create connection for Stock Names: unable to open database file
ERROR: Failed to initialize pool for Stock Names: unable to open database file
2025-02-15 21:16:21,667 - ConnectionPool - ERROR - Failed to initialize pool for Stock Names: unable to open database file
ERROR: Failed to create connection for Stock Names: unable to open database file
2025-02-15 21:16:21,668 - ConnectionPool - ERROR - Failed to create connection for Stock Names: unable to open database file
ERROR: Error managing connection for stock_names: unable to open database file
2025-02-15 21:16:21,669 - ConnectionPool - ERROR - Error managing connection for stock_names: unable to open database file
2025-02-15 21:16:21,670 - ERROR - Failed to get stock_names database connection: unable to open database file
2025-02-15 21:16:21,670 - bin.price.db_connect - ERROR - Failed to get stock_names database connection: unable to open database file

Options db Connected: 2025-02-15 21:16:21.651120

DatabaseConnectionError: Failed to get stock_names database connection: unable to open database file

Looking at the stocks that we have initialized the program with: (Remember we can always add new stocks by using the `.addStock()` method within the Pipeline Class.)

In [4]:
stocks = m.Pricedb.stocks
print(stocks)

['rddt', 'vktx']

In [7]:
# Load the closing prices for all stocks, for the get_close function the input must be a list. 
close_df = m.Pricedb.get_close(stocks)
close_df.tail()

                  rddt       vktx
date
2024-10-30  116.050003  71.750000
2024-10-31  119.300003  72.540001
2024-11-01  112.980003  72.879997
2024-11-04  109.029999  63.139999
2024-11-05  121.059998  63.299999

Load in technical indicators for each stock:

In [9]:
# Load in some technical indicators: 
indicators = {x: m.Pricedb.get_indicators(x) for x in stocks}

indicators['rddt']

,ema_fast,ema_med,ema_slow,sma_med,sma_slow,sma_fast,kama_fast,kama_med,kama_slow,macd,...,slow_stoch,mom,rsi,z_score,volatility,open,high,low,close,volume
Date,,,,,,,,,,,,,,,,,,,,,
2024-03-22,46.000000,46.000000,46.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,48.880001,51.000000,45.340000,46.000000,15936700.0
2024-03-25,54.050000,53.590000,53.146428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,47.090000,61.939999,46.080002,59.799999,24398800.0
2024-03-26,59.021927,58.220963,57.422401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,67.709999,74.900002,63.209999,65.110001,35331000.0
2024-03-27,58.530631,58.065802,57.513277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,63.759998,63.759998,55.619999,57.750000,18758300.0
2024-03-28,55.297956,55.555120,55.632485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,54.520000,55.299999,49.099998,49.320000,12608100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-30,90.144660,85.351114,76.250095,82.814001,74.420000,85.851667,93.133580,87.209069,83.897248,7.330660,...,0.862408,0.502071,0.877996,72.993348,2.043877,104.900002,118.249001,104.110001,116.050003,37764600.0
2024-10-31,98.474758,91.523639,79.219101,87.115001,76.359286,92.788334,103.533827,96.869528,91.890293,11.359757,...,1.000000,0.563770,0.901288,79.748431,2.062921,117.404999,123.599998,114.800003,119.300003,17033500.0
2024-11-01,102.619114,95.424796,81.547472,90.323001,78.002857,98.518335,106.016720,99.653483,95.109452,12.296113,...,0.946828,0.396539,0.790054,84.015870,2.100492,114.000000,115.500000,110.500000,112.980003,12024700.0
2024-11-04,104.450795,97.898469,83.442844,93.371001,79.472500,103.130001,106.605312,101.073368,96.751215,11.079795,...,0.860424,0.388033,0.767838,87.405486,2.111416,110.764999,112.980003,108.684998,109.029999,7719300.0
2024-11-05,109.196282,102.109656,86.037163,97.748000,81.420358,110.026667,110.303796,105.221433,100.574326,11.448281,...,0.860424,0.566309,0.823408,91.447618,2.140739,110.500000,122.659897,110.360001,121.059998,7939581.0